meal_plans/urls.py
from django.urls import path

from meal_plans.views import (
    MealPlanListView,
    MealPlanCreateView,
    MealPlanDetailView,
    MealPlanUpdateView,
    MealPlanDeleteView,
)

urlpatterns = [
    path("", MealPlanListView.as_view(), name="mealplans_list"),
    path("create/", MealPlanCreateView.as_view(), name="mealplan_new"),
    path("<int:pk>/", MealPlanDetailView.as_view(), name="mealplan_detail"),
    path("<int:pk>/edit", MealPlanUpdateView.as_view(), name="mealplan_edit"),
    path(
        "<int:pk>/delete", MealPlanDeleteView.as_view(), name="mealplan_delete"
    ),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("meal_plans/", include("meal_plans.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

meal_plans/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class MealPlan(models.Model):
    name = models.CharField(max_length=120)
    date = models.DateField()
    owner = models.ForeignKey(
        USER_MODEL,
        # related_name is referncing the table name in SQL
        related_name="meal_plans",
        on_delete=models.CASCADE,
        null=True,
    )
    recipes = models.ManyToManyField("recipes.Recipe", related_name="recipes")

    def __str__(self):
        return self.name

meal_plans/forms.py
# from django import forms

# from meal_plans.models import MealPlan


# I should be safe commenting out the below MealPlanForm
# given that I'm using a class-based view for MealPlanCreateView
# Doing the scrumptious-receipes project a second time,
# I'm reflecting back on why I wrote this the first time,
# and I believe it's because while creating the MealPlanCreateView,
# the instructions say to reference the RecipeCreateView and how we wrote that
# and back then, we had started off writing a FUNCTION-based view.
# Then, in a future project, we updated that function-based create view
# into a class-based create view.
# in a stretch-goal for one of the projects,
# we were told to clean up our code (the RecipeForm that we no longer needed)
# but I never got to the stretch-goal, so I still had it in my code
# CONCLUSION: the below MealPlanForm is not needed.
# Im fact, I believe this forms.py isn't needed at all
# given that all of my views are class-based views

# class MealPlanForm:
# class MealPlanForm(forms.ModelForm):
#     class Meta:
#         model = MealPlan
#         fields = [
#             "name",
#             "owner",
#             "recipes",
#             "date",
#         ]

meal_plans/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

# from meal_plans.forms import MealPlanForm
from meal_plans.models import MealPlan

from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

# COMMENT
# If user types "/meal_plans/" into the url address at the top of the page
# we DONT want to show the meal plans list page, but prompt to login.
# that's why we add the "LoginRequiredMixin"
class MealPlanListView(LoginRequiredMixin, ListView):
    model = MealPlan
    template_name = "meal_plans/list.html"
    paginate_by = 10
    # success_url = reverse_lazy("mealplans_list")

    # COMMENT FOR MYSELF
    # code given by Learn as hint.
    # https://learn-2.galvanize.com/cohorts/3189/blocks/1849/content_files/build/03-template-topics/68-meal-plans.md
    # The below code is what tells Django/database WHICH mealplans to show in the MealPlanListView.
    # If Ariana created her own meal plans, then when Ariana goes to her mealplans_list page, it should ONLY show Ariana's.
    # It Mitch created his own meal plans, then when Mitch goes to his mealplans_list page, it should ONLY show Mitch's.
    # So the below code is saying FILTER the meal plans shown on the MealPlanListView to show ONLY those where owner=requester/user
    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanCreateView(LoginRequiredMixin, CreateView):
    model = MealPlan
    template_name = "meal_plans/new.html"
    fields = ["name", "recipes", "date"]

    # it's not needed because
    # [[return redirect("mealplan_detail", pk=plan.id)]] (last line inside form_valid below)
    # will take care of the redirecting once the new mealplan is successfully created
    # success_url = reverse_lazy("mealplan_detail")

    # ??????? - Learn says to just have the code for now
    # the immediate below code was copy-pasted from recipes/views.py
    # but Learn provides a different form_valid method (see below AFTER this immediately below code block).
    # Per Learn:
    # Because of the way that Django works with the database, there's an extra step to the data saving.
    # If you're in a function view or class view, it doesn't change, really.
    # In a create class view, you'll need to implement the form_valid method to associate the user and, now, save the many-to-many relationships.
    # old code below
    # def form_valid(self, form):
    #     form.instance.owner = self.request.user
    #     return super().form_valid(form)

    # LINE BY LINE EXPLANATION
    # https://learn-2.galvanize.com/cohorts/3189/blocks/1849/content_files/build/04-view-topics/03-views-revealed.md
    # Custom handling of saving the form
    def form_valid(self, form):
        # Save the meal plan, but don't put it in the database
        plan = form.save(commit=False)
        # Assign the owner to the meal plan
        plan.owner = self.request.user
        # Now, save it to the database
        plan.save()
        # Save all of the many-to-many relationships
        form.save_m2m()
        # Redirect to the detail page for the meal plan
        return redirect("mealplan_detail", pk=plan.id)

    # FURTHER GENERAL FORMAT/EXPLANATION FROM:
    # https://learn-2.galvanize.com/cohorts/3189/blocks/1859/content_files/build/03-django-two-shot/67-django-two-shot.md
    # If you are using class views, you can do this by writing your own form_valid method.
    # The general form of a method that assigns the current user to a User property looks like this.

    # def form_valid(self, form):
    #     item = form.save(commit=False)
    #     item.user_property = self.request.user
    #     item.save()
    #     return redirect("some_view")


class MealPlanDetailView(LoginRequiredMixin, DetailView):
    model = MealPlan
    template_name = "meal_plans/detail.html"

    # COMMENT FOR MYSELF
    # code given by Learn as hint.
    # https://learn-2.galvanize.com/cohorts/3189/blocks/1849/content_files/build/03-template-topics/68-meal-plans.md
    # The below code is what tells Django/database WHICH mealplans to show in the MealPlanListView.
    # If Ariana created her own meal plans, then when Ariana goes to her mealplans_list page, it should ONLY show Ariana's.
    # It Mitch created his own meal plans, then when Mitch goes to his mealplans_list page, it should ONLY show Mitch's.
    # So the below code is saying FILTER the meal plans shown on the MealPlanListView to show ONLY those where owner=requester/user
    # -- confirmed by John's presentation, that queryset is needed for DetailView
    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanUpdateView(LoginRequiredMixin, UpdateView):
    model = MealPlan
    template_name = "meal_plans/edit.html"
    fields = ["name", "recipes", "date"]

    # COMMENT FOR MYSELF
    # this original success_url below, which comes (copy-pasted) from RecipeUpdateView in recipes/views.py,
    # takes me to "mealplans_list" once the meal plan is updated successfully
    # success_url = reverse_lazy("mealplans_list")
    # this would be fine IF everytime we successully update a mealplan_detail, we want to show the mealplans_list page
    # HOWEVER, let's say once a mealplan_detail is successfully updated, we want it to go back to that same (updated) mealplan_detail
    # the below code is the code that tells WHICH mealplan_detail to show! YAY
    def get_success_url(self) -> str:
        return reverse_lazy("mealplan_detail", args=[self.object.id])

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanDeleteView(LoginRequiredMixin, DeleteView):
    model = MealPlan
    template_name = "meal_plans/delete.html"
    success_url = reverse_lazy("mealplans_list")

    # COMMENT FOR MYSELF
    # code given by Learn as hint.
    # https://learn-2.galvanize.com/cohorts/3189/blocks/1849/content_files/build/03-template-topics/68-meal-plans.md
    # The below code is what tells Django/database WHICH mealplans to show in the MealPlanListView.
    # If Ariana created her own meal plans, then when Ariana goes to her mealplans_list page, it should ONLY show Ariana's.
    # It Mitch created his own meal plans, then when Mitch goes to his mealplans_list page, it should ONLY show Mitch's.
    # So the below code is saying FILTER the meal plans shown on the MealPlanListView to show ONLY those where owner=requester/user
    # -- confirmed by John's presentation, that queryset is needed for DetailView
    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

meal_plans/templates/meal_plans/delete.html
{% extends 'base.html' %}

{% block content %}
<main>
  <div class="delete-form">
    <form method="post">
      {% csrf_token %}
      <p>Are you sure you want to delete "{{ mealplan }}"?</p>
      {{ form.as_p }}
      <div>
        <button class="button">Delete</button>
      </div>
    </form>
  </div>
</main>
{% endblock content %}

meal_plans/templates/meal_plans/detail.html
{% extends 'base.html' %}
{% load markdownify %}

{% block content %}
<main class="tag-detail">
  <div>
    <a href="{% url 'mealplan_edit' mealplan.id %}">Edit</a>
    <a href="{% url 'mealplan_delete' mealplan.id %}">Delete</a>
  </div>
  <h2>Recipes for {{ mealplan.name }} on {{ mealplan.date | date:"M j, o" }}</h2>
  {% comment %}
  dissecting mealplan.recipes.all:
  mealplan is the MODEL associated with this view/html
  recipes is the RELATED_NAME for recipes field in the ManyToManyField within MealPlan class
  .all is just the method to get all of them
  {% endcomment %}
  {% for recipe in mealplan.recipes.all %}
  <p>
    <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
  </p>
  {% endfor %}
</main>
{% endblock content %}

meal_plans/templates/meal_plans/edit.html
{% extends "base.html" %}

{% block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control">
      <button class="button">Update</button>
    </div>
  </form>
</main>
{% endblock content %}

meal_plans/templates/meal_plans/list.html
{% extends 'base.html' %}

{% block pagination %}
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>
{% endblock pagination %}


{% block content %}
<div>
  <a href="{% url 'mealplan_new' %}">create</a>
</div>
<main class="recipe-grid">
  {% for mealplan in mealplan_list %}
  <div class="recipe-card">
    <h2 class="recipe-card-title">
      <a href="{% url 'mealplan_detail' mealplan.pk %}">{{ mealplan.name }}</a>
    </h2>

    {% for recipe in mealplan.recipes.all %}
    <p>
      <a href="{% url 'recipe_detail' recipe.pk %}">{{ recipe.name }}</a>
    </p>
    {% endfor %}
  </div>
  {% empty %}
  <div>
    <h1>No meal plans yet</h1>
    <p>
      Would you like to
      <a href="{% url 'mealplan_new' %}">create</a>
      one?
    </p>
  </div>
  {% endfor %}
</main>
{% endblock content %}

meal_plans/templates/meal_plans/new.html
{% extends 'base.html' %}

{% block content %}
<main class="recipe-form">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="control">
      <button class="button">Create</button>
    </div>
  </form>
</main>
{% endblock content %}